/* Generated by ./publish.sh — do not edit by hand.
   Baked into the page so guests need no network call to see results. */
window.PRIZE_WINNERS = {
  "publishedAt": "2026-09-12T21:51:42.925Z",
  "winners": []
};
