/* Generated by ./publish.sh — do not edit by hand.
   Baked into the page so guests need no network call to see results. */
window.PRIZE_WINNERS = {
  "publishedAt": "2026-09-13T03:47:07.866Z",
  "winners": [
    {
      "prize": "1",
      "ticket": "0719054"
    },
    {
      "prize": "2",
      "ticket": "0736463"
    },
    {
      "prize": "3",
      "ticket": "2370279"
    },
    {
      "prize": "4",
      "ticket": "0719039"
    },
    {
      "prize": "5",
      "ticket": "0383699"
    },
    {
      "prize": "6",
      "ticket": "2370236"
    },
    {
      "prize": "7",
      "ticket": "0516097"
    },
    {
      "prize": "8",
      "ticket": "0736463"
    },
    {
      "prize": "9",
      "ticket": "0394547"
    },
    {
      "prize": "10",
      "ticket": "0383685"
    },
    {
      "prize": "11",
      "ticket": "0516115"
    },
    {
      "prize": "12",
      "ticket": "0516140"
    },
    {
      "prize": "13",
      "ticket": "0719057"
    },
    {
      "prize": "14",
      "ticket": "0383692"
    },
    {
      "prize": "15",
      "ticket": "0516306"
    },
    {
      "prize": "16",
      "ticket": "0394531"
    },
    {
      "prize": "17",
      "ticket": "0719053"
    },
    {
      "prize": "18",
      "ticket": "0394695"
    },
    {
      "prize": "19",
      "ticket": "2370024"
    },
    {
      "prize": "20",
      "ticket": "0394604"
    },
    {
      "prize": "21",
      "ticket": "0383516"
    },
    {
      "prize": "22",
      "ticket": "0719064"
    },
    {
      "prize": "23",
      "ticket": "0383673"
    },
    {
      "prize": "24",
      "ticket": "0383735"
    },
    {
      "prize": "25",
      "ticket": "0736394"
    },
    {
      "prize": "26",
      "ticket": "0719053"
    },
    {
      "prize": "27",
      "ticket": "0394693"
    },
    {
      "prize": "28",
      "ticket": "0394691"
    },
    {
      "prize": "29",
      "ticket": "2370279"
    },
    {
      "prize": "30",
      "ticket": "0719120"
    },
    {
      "prize": "31",
      "ticket": "0394635"
    },
    {
      "prize": "32",
      "ticket": "0383657"
    },
    {
      "prize": "33",
      "ticket": "0719100"
    },
    {
      "prize": "34",
      "ticket": "0383675"
    },
    {
      "prize": "35",
      "ticket": "0383685"
    },
    {
      "prize": "36",
      "ticket": "0516140"
    },
    {
      "prize": "37",
      "ticket": "0719054"
    },
    {
      "prize": "38",
      "ticket": "0394643"
    },
    {
      "prize": "39",
      "ticket": "0719067"
    },
    {
      "prize": "40",
      "ticket": "0383524"
    },
    {
      "prize": "41",
      "ticket": "0516305"
    },
    {
      "prize": "42",
      "ticket": "0719040"
    },
    {
      "prize": "43",
      "ticket": "0719004"
    },
    {
      "prize": "44",
      "ticket": "0394633"
    },
    {
      "prize": "45",
      "ticket": "0383701"
    },
    {
      "prize": "46",
      "ticket": "0719114"
    },
    {
      "prize": "47",
      "ticket": "0719122"
    },
    {
      "prize": "48",
      "ticket": "0516095"
    },
    {
      "prize": "49",
      "ticket": "0383618"
    },
    {
      "prize": "50",
      "ticket": "0516302"
    },
    {
      "prize": "51",
      "ticket": "2370171"
    },
    {
      "prize": "52",
      "ticket": "0394700"
    },
    {
      "prize": "53",
      "ticket": "0719047"
    },
    {
      "prize": "54",
      "ticket": "0719146"
    },
    {
      "prize": "55",
      "ticket": "0394605"
    },
    {
      "prize": "56",
      "ticket": "0719046"
    },
    {
      "prize": "57",
      "ticket": "2370235"
    },
    {
      "prize": "58",
      "ticket": "2370261"
    },
    {
      "prize": "59",
      "ticket": "0383675"
    },
    {
      "prize": "60",
      "ticket": "0394622"
    },
    {
      "prize": "61",
      "ticket": "0394643"
    },
    {
      "prize": "62",
      "ticket": "0719072"
    },
    {
      "prize": "63",
      "ticket": "0394546"
    },
    {
      "prize": "64",
      "ticket": "0719152"
    },
    {
      "prize": "65",
      "ticket": "0383736"
    },
    {
      "prize": "66",
      "ticket": "0719151"
    },
    {
      "prize": "67",
      "ticket": "0719062"
    },
    {
      "prize": "68",
      "ticket": "0719024"
    },
    {
      "prize": "69",
      "ticket": "0719093"
    },
    {
      "prize": "70",
      "ticket": "0719093"
    },
    {
      "prize": "71",
      "ticket": "0383716"
    },
    {
      "prize": "72",
      "ticket": "0719146"
    },
    {
      "prize": "73",
      "ticket": "2370159"
    },
    {
      "prize": "74",
      "ticket": "0383720"
    },
    {
      "prize": "75",
      "ticket": "0383674"
    },
    {
      "prize": "76",
      "ticket": "0719148"
    },
    {
      "prize": "77",
      "ticket": "0719128"
    },
    {
      "prize": "78",
      "ticket": "0394550"
    },
    {
      "prize": "79",
      "ticket": "0719046"
    },
    {
      "prize": "80",
      "ticket": "0394705"
    },
    {
      "prize": "81",
      "ticket": "0736392"
    },
    {
      "prize": "82",
      "ticket": "0394642"
    },
    {
      "prize": "83",
      "ticket": "0719076"
    },
    {
      "prize": "84",
      "ticket": "0719021"
    },
    {
      "prize": "85",
      "ticket": "0719072"
    },
    {
      "prize": "86",
      "ticket": "0394540"
    },
    {
      "prize": "87",
      "ticket": "0516096"
    },
    {
      "prize": "88",
      "ticket": "0394701"
    },
    {
      "prize": "89",
      "ticket": "2370278"
    },
    {
      "prize": "90",
      "ticket": "0719047"
    },
    {
      "prize": "91",
      "ticket": "0736461"
    },
    {
      "prize": "92",
      "ticket": "0719092"
    },
    {
      "prize": "93",
      "ticket": "0719132"
    },
    {
      "prize": "94",
      "ticket": "0516104"
    },
    {
      "prize": "95",
      "ticket": "0394639"
    },
    {
      "prize": "96",
      "ticket": "0719118"
    },
    {
      "prize": "97",
      "ticket": "0719154"
    },
    {
      "prize": "98",
      "ticket": "0394641"
    },
    {
      "prize": "99",
      "ticket": "0719028"
    },
    {
      "prize": "100",
      "ticket": "0516103"
    },
    {
      "prize": "101",
      "ticket": "0383730"
    }
  ]
};
