#!/usr/bin/env node
/* Reads a two-column CSV (prize, ticket) and writes the winners into the
   site as static data. All the parsing, de-duplicating and sorting that
   used to happen on every guest's phone happens here, once. */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** RFC 4180: quoted fields, escaped quotes, CRLF. */
function parseCSV(text) {
  const out = [];
  let row = [], field = '', quoted = false;
  if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else quoted = false; }
      else field += c;
      continue;
    }
    if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field); out.push(row); row = []; field = '';
    } else field += c;
  }
  if (field !== '' || row.length) { row.push(field); out.push(row); }
  return out.map(r => r.map(s => s.trim()));
}

const norm  = (s) => String(s).toLowerCase().replace(/[^a-z0-9#]/g, '');
const clean = (v) => String(v ?? '').trim().replace(/^(-?\d+)\.0+$/, '$1');
const prizeKey = (p) =>
  Number.isFinite(Number(p)) && p !== '' ? String(Number(p)) : String(p).toUpperCase();

const PRIZE_HEADERS  = ['prize', 'prize #', 'prize no', 'prize number', 'board', '#'];
const TICKET_HEADERS = ['ticket', 'ticket #', 'ticket no', 'ticket number', 'winner', 'number'];

function toWinners(text) {
  if (/^\s*<(!doctype|html)/i.test(text)) {
    throw new Error('That URL returned a web page, not CSV. Check the sheet is shared ' +
                    'as "Anyone with the link -> Viewer".');
  }
  const table = parseCSV(text).filter(r => r.some(c => c !== ''));
  if (!table.length) return [];

  const head = table[0];
  const find = (list) => head.findIndex(h => list.some(w => norm(h) === norm(w)));
  let p = find(PRIZE_HEADERS), t = find(TICKET_HEADERS), body;
  if (p !== -1 && t !== -1) body = table.slice(1);
  else { p = 0; t = 1; body = head.some(h => /[a-z]/i.test(h)) ? table.slice(1) : table; }

  let rows = body
    .map(r => ({ prize: clean(r[p]), ticket: clean(r[t]) }))
    .filter(w => w.prize !== '' && w.ticket !== '');

  // Same prize twice means the later row was a correction.
  const byPrize = new Map();
  for (const w of rows) byPrize.set(prizeKey(w.prize), w);
  rows = [...byPrize.values()];

  return rows.sort((a, b) => {
    const na = Number(a.prize), nb = Number(b.prize);
    if (Number.isFinite(na) && Number.isFinite(nb) && na !== nb) return na - nb;
    return String(a.prize).localeCompare(String(b.prize), undefined, { numeric: true });
  });
}

const csvPath = process.argv[2];
if (!csvPath) { console.error('usage: build-winners.mjs <winners.csv>'); process.exit(1); }

const winners = toWinners(readFileSync(csvPath, 'utf8'));
const payload = { publishedAt: new Date().toISOString(), winners };

writeFileSync(join(ROOT, 'winners.js'),
  '/* Generated by ./publish.sh — do not edit by hand.\n' +
  '   Baked into the page so guests need no network call to see results. */\n' +
  'window.PRIZE_WINNERS = ' + JSON.stringify(payload, null, 2) + ';\n');

writeFileSync(join(ROOT, 'data', 'winners.json'), JSON.stringify(payload, null, 2) + '\n');

// Cache-bust winners.js so a guest can't be served yesterday's copy.
const idx = join(ROOT, 'index.html');
const stamp = Date.now().toString(36);
writeFileSync(idx, readFileSync(idx, 'utf8')
  .replace(/winners\.js(\?v=[a-z0-9]+)?(?=")/g, `winners.js?v=${stamp}`));

console.log(`${winners.length} winners`);
if (winners.length) {
  const nums = winners.map(w => w.prize);
  console.log(`prizes: ${nums[0]} – ${nums[nums.length - 1]}`);
}
